void scrn_enable_cursor(unsigned char start_line, unsigned char end_line);
void scrn_clear();
void scrn_print(char *msg);
void scrn_println(char *msg);
void scrn_set_text_colour(int foreground, int background);
int scrn_get_char_attr_byte();
void scrn_set_char_attr_byte(int byte);
void scrn_putchar(unsigned char c);
void scrn_backspace();
void scrn_newline();
void scrn_set_cursor_pos(unsigned int row, unsigned int col);
int scrn_get_cursor_row();
int scrn_get_cursor_col(); 